### 📘 Numpy (Numerical Python)

#### O que é o NumPy?

O **NumPy (Numerical Python)** é uma biblioteca do Python usada para **computação numérica eficiente**, especialmente com **arrays multidimensionais** e **operações matemáticas de alto desempenho**.

Ele é amplamente utilizado em **ciência de dados, machine learning e análise numérica**.

#### 📚 O que é uma biblioteca?

Uma biblioteca é um **conjunto de código pronto reutilizável**, que pode incluir:

* Funções
* Classes
* Objetos

✔ Permite reaproveitamento de código
✔ Evita reescrever soluções do zero
✔ Facilita o desenvolvimento

#### 🚀 Importância do NumPy em Data Science

* Alta performance em cálculos numéricos
* Base para outras bibliotecas (como Pandas, Scikit-learn, TensorFlow)
* Código otimizado (implementado em C)
* Manipulação eficiente de grandes volumes de dados
* Facilita operações matemáticas complexas

#### 🧠 Por que estudar NumPy?

* Simples e fácil de usar
* Extremamente rápido
* Open source (gratuito e aberto)
* Base de praticamente todo o ecossistema de Data Science em Python

#### 🔧 Principais recursos

* Arrays multidimensionais (ndarray)
* Operações matemáticas vetorizadas (sem loops explícitos)
* Funções estatísticas (média, desvio padrão etc.)
* Álgebra linear
* Constantes matemáticas (π, e)
* Manipulação eficiente de dados numéricos

---

### ⚙️ Como usar o NumPy

#### 📦 Instalação

In [1]:
!pip install numpy

#### 📥 Importação

In [2]:
import numpy as np  # "np" é o alias padrão

---

### 📊 Arrays no NumPy

#### 🧩 O que é um ndarray?

O **ndarray (n-dimensional array)** é a estrutura principal do NumPy.

Ele é um array multidimensional que:

* Armazena elementos do mesmo tipo
* Possui tamanho fixo (não pode ser alterado após criação)
* É mais rápido que listas do Python

#### ⚠️ Características importantes

* Todos os elementos têm o mesmo tipo (`dtype`)
* Estrutura fixa (não cresce dinamicamente como listas)
* Otimizado para performance

---

### 🧾 Componentes de um array

Um `ndarray` possui propriedades importantes:

#### 📐 `shape`

Indica o formato do array (linhas, colunas, dimensões).

#### 🔢 `ndim`

Indica o número de dimensões do array.

#### 🧬 `dtype`

Define o tipo dos dados armazenados (int, float, etc.).

✔ Essencial porque o NumPy é baseado em tipagem forte (inspirado em C), o que garante eficiência.

---

### ⚠️ Referência vs cópia de arrays

#### 🔁 Passagem por referência (padrão)

Quando você faz:

In [3]:
a = np.array([1, 2, 3])
b = a

👉 `b` NÃO é uma cópia
👉 Ambos apontam para o mesmo array
👉 Mudanças em `b` afetam `a`

#### 📋 Criando uma cópia independente

In [4]:
b = a.copy()

✔ Agora `b` é independente

✔ Alterações não afetam o original

In [5]:
import numpy as np

arr = np.array([1, 2, 3])        # A partir de lista
arr = np.zeros((2, 2))           # Matriz de zeros
arr = np.identity(3)             # Matriz identidade
arr = np.array([[1, 2], [3, 4]])  # A partir de lista de listas
arr

array([[1, 2],
       [3, 4]])

In [6]:
arr.shape # Retorna a forma (shape) do array

(2, 2)

In [7]:
arr.ndim # Retorna o número de dimensões do array

2

In [8]:
arr.dtype # Retorna o tipo de dados dos elementos do array

dtype('int64')

In [9]:
# Referência de array
arr_1 = np.arange(5)
arr_2 = arr_1.copy()  # Cria uma cópia do array
arr_2[0] = 100  # Modifica o primeiro elemento de arr_2
print("arr_1:", arr_1)  # arr_1 permanece inalterado
print("arr_2:", arr_2)  # arr_2 é modificado

arr_1: [0 1 2 3 4]
arr_2: [100   1   2   3   4]


---

### 🧮 Definição de computação vetorizada

A **computação vetorizada** é um estilo de processamento em que operações são aplicadas diretamente em **arrays inteiros**, sem a necessidade de loops explícitos (como `for`).

Isso é possível porque o NumPy executa operações em código otimizado (C), tornando os cálculos muito mais rápidos e eficientes.

#### ➕ Aritmética

##### 🔁 Operações entre arrays

* As operações são feitas elemento por elemento
* Não é necessário usar laços de repetição

Exemplo conceitual:

* `[1, 2, 3] + [4, 5, 6] → [5, 7, 9]`

##### 🔢 Operações com escalares

* O escalar é aplicado a todos os elementos do array
* Isso é chamado de **broadcasting**

Exemplo conceitual:

* `[1, 2, 3] + 10 → [11, 12, 13]`

#### ⚖️ Comparações

##### 📊 Comparação entre arrays

* O resultado é um array de valores booleanos (`True` ou `False`)
* Cada posição é avaliada individualmente

Exemplo conceitual:

* `[1, 2, 3] > [0, 2, 4] → [True, False, False]`

##### 🔍 Comparação com escalar

* O escalar é aplicado a todos os elementos
* O resultado também é um array booleano

Exemplo conceitual:

* `[1, 2, 3] > 1 → [False, True, True]`

##### 🔗 Combinações de comparações

É possível combinar múltiplas condições lógicas usando operadores como:

* `&` (E lógico)
* `|` (OU lógico)
* `~` (negação)

Essas combinações permitem criar filtros mais complexos em arrays.

In [10]:
arr_1 = np.arange(5)
arr_2 = np.arange(5, 10)

print(arr_1)
print(arr_2)

# Soma
soma = arr_1 + arr_2
print(soma)

# Operações com escalar
arr = np.array([1, 2, 3])
print(arr * 2)  # Multiplicação por escalar

# Comparações entre arrays
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([3, 2, 1])
print(arr_1 > arr_2)  # Comparação elemento a elemento

# Comparação com escalar
arr = np.array([1, 2, 3])
print(arr > 2)  # Retorna um array booleano indicando quais elementos são maiores que 2

# Combinação de comparações
arr = np.array([1, 2, 3, 4, 5])
print((arr > 2) & (arr < 5))  # Retorna um array booleano indicando quais elementos estão entre 2 e 5 (exclusivo)

[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11 13]
[2 4 6]
[False False  True]
[False False  True]
[False False  True  True False]


---

### ✂️ Indexação e fatiamento (slice)

A **indexação** permite acessar elementos específicos de um array.

O **fatiamento (slice)** permite acessar subconjuntos do array.

* Funciona de forma semelhante às listas do Python
* Pode ser aplicado em arrays multidimensionais
* Permite selecionar partes específicas de dados de forma eficiente

Exemplo conceitual:

* `arr[0]` → primeiro elemento
* `arr[1:3]` → intervalo de elementos
* `arr[:, 0]` → primeira coluna de uma matriz

In [11]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Acessa o primeiro elemento
print(arr[1:4])  # Acessa os elementos do índice 1 ao 3 (4 é exclusivo)
print(arr[-1])  # Acessa o último elemento
print(arr[::2])  # Acessa os elementos de 2 em 2

10
[20 30 40]
50
[10 30 50]


---

### 📊 Estatística para NumPy

A estatística é a área da matemática que estuda métodos de **coleta, organização, análise e interpretação de dados**.

Ela é fundamental em ciência de dados, pois permite transformar dados brutos em informações úteis para tomada de decisão.

#### 📈 Estatística descritiva

A estatística descritiva tem como objetivo resumir e organizar dados, facilitando sua compreensão.

##### 📍 Medidas de tendência central

São medidas que representam um **valor central ou típico** de um conjunto de dados.

* 📌 Média: soma dos valores dividida pela quantidade de elementos
* 📌 Mediana: valor central quando os dados estão ordenados
* 📌 Moda: valor que mais se repete

Essas medidas ajudam a entender onde os dados “se concentram”.

##### 📊 Percentis

Os **percentis** dividem um conjunto de dados ordenado em 100 partes iguais.

* 📌 Indicam a posição relativa de um valor dentro do conjunto
* 📌 Exemplo: o percentil 90 indica que 90% dos dados estão abaixo daquele valor

São muito usados para análise de distribuição e comparação de desempenho.

##### 📏 Valores limites

São valores que representam os **extremos de um conjunto de dados**.

* 📌 Valor mínimo (menor elemento)
* 📌 Valor máximo (maior elemento)

Eles ajudam a entender a amplitude dos dados.

##### 📉 Desvio padrão

O **desvio padrão** mede o grau de dispersão dos dados em relação à média.

* 📌 Valores baixos → dados próximos da média
* 📌 Valores altos → dados muito espalhados

É uma das principais medidas de variabilidade.


In [20]:
# criar array de uma lista com valores aleatórios de 1 a 100
arr = np.random.randint(1, 101, size=10)
arr

array([70, 11, 26, 29,  1, 73, 89, 83, 97, 24], dtype=int32)

In [23]:
print(arr.max())   # Valor máximo
print(arr.min())   # Valor mínimo
print(arr.argmax())  # Índice do valor máximo
print(arr.argmin())  # Índice do valor mínimo
print(arr.mean())  # Média
print(arr.std())  # Desvio padrão
print(arr.sum())  # Soma
print(arr.cumsum())  # Soma acumulada
print(arr.prod())  # Produto
print(arr.cumprod())  # Produto acumulado


97
1
8
4
50.3
33.707714250598485
503
[ 70  81 107 136 137 210 299 382 479 503]
728846388510240
[             70             770           20020          580580
          580580        42382340      3772028260    313078345580
  30368599521260 728846388510240]


In [ ]:
# Selecione os valores que se distanciam da média até um desvio padrão
bool_idx = (arr > arr.mean() - arr.std()) & (arr < arr.mean() + arr.std())
arr[bool_idx]  # Retorna os valores que atendem à condição

array([70, 26, 29, 73, 83, 24], dtype=int32)

---

### 📘 Definição de funções universais em NumPy

#### ⚙️ **ufuncs (universal functions)**

As *ufuncs* são funções do NumPy projetadas para operar de forma eficiente em arrays, aplicando transformações elemento por elemento.

* 🚀 São funções vetorizadas, ou seja, atuam diretamente em arrays inteiros sem a necessidade de loops explícitos em Python.
* ⚡ São altamente otimizadas em C, o que as torna muito mais rápidas que operações com loops comuns.
* 🔁 Podem receber e retornar diferentes quantidades de entradas e saídas.

#### 🔢 Tipos de ufuncs:

* **Unárias**: recebem apenas um array de entrada
  Ex: `np.sqrt(x)`, `np.exp(x)`, `np.sin(x)` 🌿

* **Binárias**: recebem dois arrays de entrada
  Ex: `np.add(x, y)`, `np.multiply(x, y)`, `np.maximum(x, y)` 🔗

#### 📤 Saídas:

* 📦 Geralmente retornam um único array como resultado.
* 🧩 Algumas ufuncs podem retornar múltiplos resultados (menos comum), dependendo da operação.

In [29]:
arr = arr = np.random.randint(1, 81, size=10)
print(arr)
print(np.median(arr))  # Mediana
print(np.percentile(arr, 25))  # Percentil 25
print(np.percentile(arr, 75))  # Percentil 75

[ 6  8 53 47 75  8 14 17 48 34]
25.5
9.5
47.75


In [ ]:
arr1 = np.array([9, 9, 9, 9, 9])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.add(arr1, arr2))  # Soma elemento a elemento
print(np.maximum(arr1, arr2))   # Retorna o valor máximo elemento a elemento

[15 16 17 18 19]
[ 9  9  9  9 10]
