### 📘 Numpy (Numerical Python)

#### O que é o NumPy?

O **NumPy (Numerical Python)** é uma biblioteca do Python usada para **computação numérica eficiente**, especialmente com **arrays multidimensionais** e **operações matemáticas de alto desempenho**.

Ele é amplamente utilizado em **ciência de dados, machine learning e análise numérica**.

#### 📚 O que é uma biblioteca?

Uma biblioteca é um **conjunto de código pronto reutilizável**, que pode incluir:

* Funções
* Classes
* Objetos

✔ Permite reaproveitamento de código
✔ Evita reescrever soluções do zero
✔ Facilita o desenvolvimento

#### 🚀 Importância do NumPy em Data Science

* Alta performance em cálculos numéricos
* Base para outras bibliotecas (como Pandas, Scikit-learn, TensorFlow)
* Código otimizado (implementado em C)
* Manipulação eficiente de grandes volumes de dados
* Facilita operações matemáticas complexas

#### 🧠 Por que estudar NumPy?

* Simples e fácil de usar
* Extremamente rápido
* Open source (gratuito e aberto)
* Base de praticamente todo o ecossistema de Data Science em Python

#### 🔧 Principais recursos

* Arrays multidimensionais (ndarray)
* Operações matemáticas vetorizadas (sem loops explícitos)
* Funções estatísticas (média, desvio padrão etc.)
* Álgebra linear
* Constantes matemáticas (π, e)
* Manipulação eficiente de dados numéricos

---

### ⚙️ Como usar o NumPy

#### 📦 Instalação

In [1]:
!pip install numpy

#### 📥 Importação

In [2]:
import numpy as np  # "np" é o alias padrão

---

### 📊 Arrays no NumPy

#### 🧩 O que é um ndarray?

O **ndarray (n-dimensional array)** é a estrutura principal do NumPy.

Ele é um array multidimensional que:

* Armazena elementos do mesmo tipo
* Possui tamanho fixo (não pode ser alterado após criação)
* É mais rápido que listas do Python

#### ⚠️ Características importantes

* Todos os elementos têm o mesmo tipo (`dtype`)
* Estrutura fixa (não cresce dinamicamente como listas)
* Otimizado para performance

---

### 🧾 Componentes de um array

Um `ndarray` possui propriedades importantes:

#### 📐 `shape`

Indica o formato do array (linhas, colunas, dimensões).

#### 🔢 `ndim`

Indica o número de dimensões do array.

#### 🧬 `dtype`

Define o tipo dos dados armazenados (int, float, etc.).

✔ Essencial porque o NumPy é baseado em tipagem forte (inspirado em C), o que garante eficiência.

---

### ⚠️ Referência vs cópia de arrays

#### 🔁 Passagem por referência (padrão)

Quando você faz:

In [3]:
a = np.array([1, 2, 3])
b = a

👉 `b` NÃO é uma cópia
👉 Ambos apontam para o mesmo array
👉 Mudanças em `b` afetam `a`

#### 📋 Criando uma cópia independente

In [4]:
b = a.copy()

✔ Agora `b` é independente

✔ Alterações não afetam o original

In [5]:
import numpy as np

arr = np.array([1, 2, 3])        # A partir de lista
arr = np.zeros((2, 2))           # Matriz de zeros
arr = np.identity(3)             # Matriz identidade
arr = np.array([[1, 2], [3, 4]])  # A partir de lista de listas
arr

array([[1, 2],
       [3, 4]])

In [6]:
arr.shape # Retorna a forma (shape) do array

(2, 2)

In [7]:
arr.ndim # Retorna o número de dimensões do array

2

In [8]:
arr.dtype # Retorna o tipo de dados dos elementos do array

dtype('int64')

In [9]:
# Referência de array
arr_1 = np.arange(5)
arr_2 = arr_1.copy()  # Cria uma cópia do array
arr_2[0] = 100  # Modifica o primeiro elemento de arr_2
print("arr_1:", arr_1)  # arr_1 permanece inalterado
print("arr_2:", arr_2)  # arr_2 é modificado

arr_1: [0 1 2 3 4]
arr_2: [100   1   2   3   4]


---

### 🧮 Definição de computação vetorizada

A **computação vetorizada** é um estilo de processamento em que operações são aplicadas diretamente em **arrays inteiros**, sem a necessidade de loops explícitos (como `for`).

Isso é possível porque o NumPy executa operações em código otimizado (C), tornando os cálculos muito mais rápidos e eficientes.

#### ➕ Aritmética

##### 🔁 Operações entre arrays

* As operações são feitas elemento por elemento
* Não é necessário usar laços de repetição

Exemplo conceitual:

* `[1, 2, 3] + [4, 5, 6] → [5, 7, 9]`

##### 🔢 Operações com escalares

* O escalar é aplicado a todos os elementos do array
* Isso é chamado de **broadcasting**

Exemplo conceitual:

* `[1, 2, 3] + 10 → [11, 12, 13]`

#### ⚖️ Comparações

##### 📊 Comparação entre arrays

* O resultado é um array de valores booleanos (`True` ou `False`)
* Cada posição é avaliada individualmente

Exemplo conceitual:

* `[1, 2, 3] > [0, 2, 4] → [True, False, False]`

##### 🔍 Comparação com escalar

* O escalar é aplicado a todos os elementos
* O resultado também é um array booleano

Exemplo conceitual:

* `[1, 2, 3] > 1 → [False, True, True]`

##### 🔗 Combinações de comparações

É possível combinar múltiplas condições lógicas usando operadores como:

* `&` (E lógico)
* `|` (OU lógico)
* `~` (negação)

Essas combinações permitem criar filtros mais complexos em arrays.

In [10]:
arr_1 = np.arange(5)
arr_2 = np.arange(5, 10)

print(arr_1)
print(arr_2)

# Soma
soma = arr_1 + arr_2
print(soma)

# Operações com escalar
arr = np.array([1, 2, 3])
print(arr * 2)  # Multiplicação por escalar

# Comparações entre arrays
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([3, 2, 1])
print(arr_1 > arr_2)  # Comparação elemento a elemento

# Comparação com escalar
arr = np.array([1, 2, 3])
print(arr > 2)  # Retorna um array booleano indicando quais elementos são maiores que 2

# Combinação de comparações
arr = np.array([1, 2, 3, 4, 5])
print((arr > 2) & (arr < 5))  # Retorna um array booleano indicando quais elementos estão entre 2 e 5 (exclusivo)

[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11 13]
[2 4 6]
[False False  True]
[False False  True]
[False False  True  True False]


---

### ✂️ Indexação e fatiamento (slice)

A **indexação** permite acessar elementos específicos de um array.

O **fatiamento (slice)** permite acessar subconjuntos do array.

* Funciona de forma semelhante às listas do Python
* Pode ser aplicado em arrays multidimensionais
* Permite selecionar partes específicas de dados de forma eficiente

Exemplo conceitual:

* `arr[0]` → primeiro elemento
* `arr[1:3]` → intervalo de elementos
* `arr[:, 0]` → primeira coluna de uma matriz

In [11]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Acessa o primeiro elemento
print(arr[1:4])  # Acessa os elementos do índice 1 ao 3 (4 é exclusivo)
print(arr[-1])  # Acessa o último elemento
print(arr[::2])  # Acessa os elementos de 2 em 2

10
[20 30 40]
50
[10 30 50]


---

### 📊 Estatística para NumPy

A estatística é a área da matemática que estuda métodos de **coleta, organização, análise e interpretação de dados**.

Ela é fundamental em ciência de dados, pois permite transformar dados brutos em informações úteis para tomada de decisão.

#### 📈 Estatística descritiva

A estatística descritiva tem como objetivo resumir e organizar dados, facilitando sua compreensão.

##### 📍 Medidas de tendência central

São medidas que representam um **valor central ou típico** de um conjunto de dados.

* 📌 Média: soma dos valores dividida pela quantidade de elementos
* 📌 Mediana: valor central quando os dados estão ordenados
* 📌 Moda: valor que mais se repete

Essas medidas ajudam a entender onde os dados “se concentram”.

##### 📊 Percentis

Os **percentis** dividem um conjunto de dados ordenado em 100 partes iguais.

* 📌 Indicam a posição relativa de um valor dentro do conjunto
* 📌 Exemplo: o percentil 90 indica que 90% dos dados estão abaixo daquele valor

São muito usados para análise de distribuição e comparação de desempenho.

##### 📏 Valores limites

São valores que representam os **extremos de um conjunto de dados**.

* 📌 Valor mínimo (menor elemento)
* 📌 Valor máximo (maior elemento)

Eles ajudam a entender a amplitude dos dados.

##### 📉 Desvio padrão

O **desvio padrão** mede o grau de dispersão dos dados em relação à média.

* 📌 Valores baixos → dados próximos da média
* 📌 Valores altos → dados muito espalhados

É uma das principais medidas de variabilidade.


In [12]:
# criar array de uma lista com valores aleatórios de 1 a 100
arr = np.random.randint(1, 101, size=10)
arr

array([30, 90, 16, 58, 22, 90, 47, 11, 32,  6], dtype=int32)

In [13]:
print(arr.max())   # Valor máximo
print(arr.min())   # Valor mínimo
print(arr.argmax())  # Índice do valor máximo
print(arr.argmin())  # Índice do valor mínimo
print(arr.mean())  # Média
print(arr.std())  # Desvio padrão
print(arr.sum())  # Soma
print(arr.cumsum())  # Soma acumulada
print(arr.prod())  # Produto
print(arr.cumprod())  # Produto acumulado


90
6
1
9
40.2
29.040661149498643
402
[ 30 120 136 194 216 306 353 364 396 402]
492457439232000
[             30            2700           43200         2505600
        55123200      4961088000    233171136000   2564882496000
  82076239872000 492457439232000]


In [14]:
# Selecione os valores que se distanciam da média até um desvio padrão
bool_idx = (arr > arr.mean() - arr.std()) & (arr < arr.mean() + arr.std())
arr[bool_idx]  # Retorna os valores que atendem à condição

array([30, 16, 58, 22, 47, 32], dtype=int32)

---

### 📘 Funções universais em NumPy

#### ⚙️ **ufuncs (universal functions)**

As *ufuncs* são funções do NumPy projetadas para operar de forma eficiente em arrays, aplicando transformações elemento por elemento.

* 🚀 São funções vetorizadas, ou seja, atuam diretamente em arrays inteiros sem a necessidade de loops explícitos em Python.
* ⚡ São altamente otimizadas em C, o que as torna muito mais rápidas que operações com loops comuns.
* 🔁 Podem receber e retornar diferentes quantidades de entradas e saídas.

#### 🔢 Tipos de ufuncs:

* **Unárias**: recebem apenas um array de entrada
  Ex: `np.sqrt(x)`, `np.exp(x)`, `np.sin(x)` 🌿

* **Binárias**: recebem dois arrays de entrada
  Ex: `np.add(x, y)`, `np.multiply(x, y)`, `np.maximum(x, y)` 🔗

#### 📤 Saídas:

* 📦 Geralmente retornam um único array como resultado.
* 🧩 Algumas ufuncs podem retornar múltiplos resultados (menos comum), dependendo da operação.

In [15]:
arr = arr = np.random.randint(1, 81, size=10)
print(arr)
print(np.median(arr))  # Mediana
print(np.percentile(arr, 25))  # Percentil 25
print(np.percentile(arr, 75))  # Percentil 75

[40 19 75 42 80 54 26  1 34 23]
37.0
23.75
51.0


In [16]:
arr1 = np.array([9, 9, 9, 9, 9])
arr2 = np.array([6, 7, 8, 9, 10])

print(np.add(arr1, arr2))  # Soma elemento a elemento
print(np.maximum(arr1, arr2))   # Retorna o valor máximo elemento a elemento

[15 16 17 18 19]
[ 9  9  9  9 10]


---

### 📊 Álgebra Linear

A álgebra linear é fundamental para a ciência de dados porque permite representar e manipular dados de forma estruturada usando vetores e matrizes, o que facilita cálculos e modelagem de problemas complexos.

Em Python, bibliotecas como o **NumPy** permitem trabalhar com esses conceitos por meio do objeto **ndarray**, que representa vetores e matrizes de forma eficiente.

Entre as principais operações da álgebra linear estão:

- ➕ Adição de vetores e matrizes  
- ➖ Subtração  
- ✖️ Multiplicação por escalar  
- 🧩 Multiplicação de matrizes  
- 📐 Determinante  
- 🔄 Transposição  
- 🔁 Inversão de matriz  

Essas operações são essenciais para algoritmos de machine learning, análise de dados e computação científica.


In [26]:
mtx = np.eye(3) # Matriz identidade 3x3
print(mtx)
print()

mtx = np.eye(3) + [1, 1.5, 3] # soma de matriz identidade com um vetor
print(mtx)
print()

vet = np.array([1, 2, 3])

# Multiplicação de matriz por vetor
res = mtx @ vet
print(res)
print()

# Determinante de uma matriz
det = np.linalg.det(mtx)
print(det)
print()

# Transposta de uma matriz
transposta = mtx.T
print(transposta)
print()

# Inversa de uma matriz
inversa = np.linalg.inv(mtx)
print(inversa)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[2.  1.5 3. ]
 [1.  2.5 3. ]
 [1.  1.5 4. ]]

[14. 15. 16.]

6.500000000000001

[[2.  1.  1. ]
 [1.5 2.5 1.5]
 [3.  3.  4. ]]

[[ 0.84615385 -0.23076923 -0.46153846]
 [-0.15384615  0.76923077 -0.46153846]
 [-0.15384615 -0.23076923  0.53846154]]


---

Exercício 1. Faça uma função que receba um array como entrada, remova o primeiro e o último elementos do array e retorne um novo array contendo os elementos restantes

In [ ]:
def remove_first_last(arr):
    if len(arr) <= 2:
        return np.array([])  # Retorna um array vazio se o array tiver 2 ou menos elementos
    return arr[1:-1]  # Retorna um novo array sem o primeiro e o último elementos

# Exemplo de uso
arr = np.array([1, 2, 3, 4, 5])
result = remove_first_last(arr)
print(result)  # Saída: [2 3 4]

[2 3 4]


Exercício 2. Crie um array com elementos de 0 a 100 e calcume a soma de todos os valores pares

In [ ]:
arr = np.arange(101)  # Cria um array com elementos de 0 a 100
print(arr)
pares = arr[arr % 2 == 0]  # Seleciona apenas os valores pares
print(pares)
soma_pares = pares.sum()  # Calcula a soma dos valores pares
print(soma_pares)  # Saída: 2550

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
2550


Exercício 3. Gere um array A contendo todos os números ímpares entre 0 e 100. A partir de A, crie outro array que contenha a soma cumulativa dos elementos de A que são divisíveis por 3 e 5 simultaneamente

In [29]:
arr = np.arange(101)  # Cria um array com elementos de 0 a 100
A = arr[arr % 2 == 1]  # Seleciona apenas os valores ímpares
print(A)

B = A[(A % 3 == 0) & (A % 5 == 0)]  # Seleciona os elementos divisíveis por 3 e 5
print(B)

soma_cumulativa = np.cumsum(B)  # Calcula a soma cumulativa dos elementos de B
print(soma_cumulativa)  # Imprime a soma cumulativa dos elementos de B

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[15 45 75]
[ 15  60 135]


Exercício 4. Faça uma função que dados dois vetores (valores e pesos), calcule a média ponderada de valores com seus respectivos pesos. Observação: não é permitido utilizar a função np.average do Numpy

In [30]:
def media_ponderada(valores, pesos):
    if len(valores) != len(pesos):
        raise ValueError("Os vetores de valores e pesos devem ter o mesmo comprimento.")
    
    soma_ponderada = np.sum(valores * pesos)  # Calcula a soma ponderada
    soma_pesos = np.sum(pesos)  # Calcula a soma dos pesos
    
    if soma_pesos == 0:
        raise ValueError("A soma dos pesos não pode ser zero.")
    
    media = soma_ponderada / soma_pesos  # Calcula a média ponderada
    return media

# Exemplo de uso
valores = np.array([10, 20, 30])
pesos = np.array([1, 2, 3])
resultado = media_ponderada(valores, pesos)
print(resultado)  # Saída: 23.333333333333332

23.333333333333332


Exercício 5. Considere um array bidimensional no qual cada vetor de uma dimensão possui 3 pontuações que um jogador recebeu em 3 provas distintas. Faça uma função que dado esse array, retorne a prova com maior soma de pontuações.

In [ ]:
def prova_com_maior_soma(pontuacoes):
    soma_provas = np.sum(pontuacoes, axis=0)  # Soma as pontuações de cada prova
    indice_maior_soma = np.argmax(soma_provas)  # Encontra o índice da prova com maior soma
    return indice_maior_soma

# Exemplo de uso
pontuacoes = np.array([[10, 20, 30], [15, 25, 35], [5, 10, 15]])
indice_prova = prova_com_maior_soma(pontuacoes)
print(indice_prova)  # Saída: 2

2


Exercício 6. Você é um professor e está organizando as notas de seus alunos. Para tanto, você precisa realizar algumas tarefas, como:

- Determinar a média das notas
- Determinar a maior e a menor notas e os alunos que as tiraram
- Determinar as notas dos alunos aprovados e reprovados

Considere que são aprovados os alunos com notas maiores ou iguais a 5.0.

In [32]:
def analisar_notas(nomes, notas):
    media = np.mean(notas)  # Calcula a média das notas
    maior_nota = np.max(notas)  # Determina a maior nota
    menor_nota = np.min(notas)  # Determina a menor nota
    
    aluno_maior_nota = nomes[np.argmax(notas)]  # Aluno com a maior nota
    aluno_menor_nota = nomes[np.argmin(notas)]  # Aluno com a menor nota
    
    aprovados = nomes[notas >= 5.0]  # Alunos aprovados
    reprovados = nomes[notas < 5.0]   # Alunos reprovados
    
    return media, maior_nota, menor_nota, aluno_maior_nota, aluno_menor_nota, aprovados, reprovados

# Exemplo de uso
nomes = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve'])
notas = np.array([7.5, 4.0, 8.0, 3.5, 6.0])
resultados = analisar_notas(nomes, notas)
print("Média das notas:", resultados[0])
print("Maior nota:", resultados[1], "Aluno:", resultados[3])
print("Menor nota:", resultados[2], "Aluno:", resultados[4])
print("Alunos aprovados:", resultados[5])
print("Alunos reprovados:", resultados[6])

Média das notas: 5.8
Maior nota: 8.0 Aluno: Charlie
Menor nota: 3.5 Aluno: David
Alunos aprovados: ['Alice' 'Charlie' 'Eve']
Alunos reprovados: ['Bob' 'David']



Exercício 7. Um quadrado mágico é todo quadrado de lado $n$ em que os inteiros de $1$ a $n^2$ aparecem sem repetição e em que as somas dos elementos das linhas, colunas e diagonais são iguais.

Faça uma função que recebe uma matriz quadrada e que verifique se ela é um quadrado mágico ou não.

Exemplo: O quadrado $\begin{bmatrix} 2 & 9 & 4 \\ 7 & 5 & 3 \\ 6 & 1 & 8 \end{bmatrix}$ é um quadrado mágico. Observe que as linhas, colunas e diagonais possuem soma igual a 15.

In [34]:
def eh_quadrado_magico(matriz):
    n = matriz.shape[0]  # Tamanho da matriz
    if matriz.shape[0] != matriz.shape[1]:
        return False  # Não é quadrada
    
    numeros_esperados = set(range(1, n**2 + 1))
    numeros_matriz = set(matriz.flatten())
    
    if numeros_esperados != numeros_matriz:
        return False  # Os números não são os esperados
    
    soma_magica = n * (n**2 + 1) // 2  # Soma mágica para um quadrado de lado n
    
    # Verificar linhas
    for i in range(n):
        if np.sum(matriz[i, :]) != soma_magica:
            return False
    
    # Verificar colunas
    for j in range(n):
        if np.sum(matriz[:, j]) != soma_magica:
            return False
    
    # Verificar diagonais
    if np.sum(np.diag(matriz)) != soma_magica:
        return False
    if np.sum(np.diag(np.fliplr(matriz))) != soma_magica:
        return False
    
    return True

# Exemplo de uso
matriz = np.array([[2, 9, 4], [7, 5, 3], [6, 1, 8]])
print(eh_quadrado_magico(matriz))  # Saída: True

True
